" ~/.vimrc: executed by ViM for configuration

" Behaviour
set nocompatible "disable Vi compatibility
set pastetoggle=<F3>

" Movement and search
set smartcase "ignore case until a uppercase letter is explicitly specified

" Text display
set number
set relativenumber
set colorcolumn=80
highlight ColorColumn ctermbg=grey

" Syntax, highlighting and spelling
set hlsearch "highlight all search matches

" Multiple windows
set hidden "dont unload a buffer when it is hidden

" Messages and info
set showmode "show current editor mode
set showcmd "show partial commands being typed

" Tabs and indenting
set tabstop=4
set expandtab "converts Tab's to whitespaces
set softtabstop=4 "tab key indents by four spaces
set shiftwidth=4 "width for autoindents
set smartindent
set shiftround "round to shiftwidth when indenting

" Reading and writing files
set nobackup
set noswapfile

" Command line editing
set wildmode=full

" Text encoding

" Plugin settings
if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif
